name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Run funcs
        run: go test -v ./funcs